name: Build Linux

on:
  workflow_dispatch

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2
    - name: Install Requirements
      run: apt-get install libasound2-dev
    - name: Build
      run: cargo build
